(maint): specify components to install
- removes need to install `rust-docs` at all

This is needed as `rust-docs` is unavailable for M1 mac which results in the error below

```bash
Rust is installed now. Great!
error: toolchain 'stable-aarch64-apple-darwin' does not contain component 'rust-docs' for target 'aarch64-apple-darwin'
```